#!/usr/bin/python
# -*- coding: utf-8 -*-
ahoratram = {'deva': 'अहोरात्रम्', 'iast': 'Ahorātram', 'HK': 'ahorAtram', 'en': 'Ahoratram', 'telugu': 'అహోరాత్రమ్'}
adhika = {'deva': 'अधिक', 'iast': 'Adhika', 'HK': 'adhika', 'en': 'Adhika', 'telugu': 'అధిక'}
samvatsara = {'deva': 'संवत्सरः', 'iast': 'Saṃvatsaraḥ', 'HK': 'saMvatsaraH', 'en': 'Samvatsara', 'telugu': 'సంవత్సరః'}
ekadashi = {'deva': 'एकादशी', 'iast': 'Ekādaśī', 'HK': 'ekAdazI', 'en': 'Ekadashi', 'telugu': 'ఏకాదశీ'}
sarva = {'deva': 'सर्व', 'iast': 'Sarva', 'HK': 'sarva', 'en': 'Sarva', 'telugu': 'సర్వ'}
smartha = {'deva': 'स्मार्थ', 'iast': 'Smārtha', 'HK': 'smArtha', 'en': 'Smartha', 'telugu': 'స్మార్థ'}
vaishnava = {'deva': 'वैष्णव', 'iast': 'Vaiṣṇava', 'HK': 'vaiSNava', 'en': 'Vaishnava', 'telugu': 'వైష్ణవ'}
pradosham = {'deva': 'प्रदोष-व्रतम्', 'iast': 'Pradoṣa-vratam', 'HK': 'pradoSa-vratam', 'en': 'Pradosha-Vratam', 'telugu': 'ప్రదోష-వ్రతమ్'}
chaturthi = {'deva': 'सङ्कटहर-चतुर्थी', 'iast': 'Saṅkaṭahara-chaturthī', 'HK': 'saGkaTahara-caturthI', 'en': 'Sankatahara-Chaturthi', 'telugu': 'సఙ్కటహర-చతుర్థీ'}
maha = {'deva': 'महा', 'iast': 'Mahā', 'HK': 'mahA', 'en': 'Maha', 'telugu': 'మహా'}
arambham = {'deva': 'आरम्भः', 'iast': 'Ārambhaḥ', 'HK': 'ArambhaH', 'en': 'Arambha', 'telugu': 'ఆరమ్భః'}
navaratri_start = {'deva': 'नवरात्रि-आरम्भः', 'iast': 'Navarātri-ārambhaḥ', 'HK': 'navarAtri-ArambhaH', 'en': 'Navaratri-Arambha', 'telugu': 'నవరాత్రి-ఆరమ్భః'}
lalitapanchami = {'deva': 'ललिता~पञ्चमी', 'iast': 'Lalitā~Pañchamī', 'HK': 'lalitA~paJcamI', 'en': 'Lalita Panchami', 'telugu': 'లలితా~పఞ్చమీ'}
durgashtami = {'deva': 'दुर्गाष्टमी', 'iast': 'Durgāṣṭamī', 'HK': 'durgASTamI', 'en': 'Durgashtami', 'telugu': 'దుర్గాష్టమీ'}
mahanavami = {'deva': 'महानवमी/सरस्वती-पूजा', 'iast': 'Mahānavamī/Sarasvatī-pūjā', 'HK': 'mahAnavamI/sarasvatI-pUjA', 'en': 'Mahanavami/Sarasvati-Puja', 'telugu': 'మహానవమీ/సరస్వతీ-పూజా'}
vijayadashami = {'deva': 'विजयदशमी', 'iast': 'Vijayadaśamī', 'HK': 'vijayadazamI', 'en': 'Vijayadashami', 'telugu': 'విజయదశమీ'}
dipavali = {'deva': 'दीपावली', 'iast': 'Dīpāvalī', 'HK': 'dIpAvalI', 'en': 'Dipavali', 'telugu': 'దీపావలీ'}
skanda = {'deva': 'स्कन्द~', 'iast': 'Skanda~', 'HK': 'skanda~', 'en': 'Skanda ', 'telugu': 'స్కన్ద~'}
shashthi = {'deva': 'षष्ठी-व्रतम्', 'iast': 'Ṣaṣṭhī-vratam', 'HK': 'SaSThI-vratam', 'en': 'Shashthi-Vratam', 'telugu': 'షష్ఠీ-వ్రతమ్'}
vaikuntha = {'deva': 'वैकुण्ठ', 'iast': 'Vaikuṇṭha', 'HK': 'vaikuNTha', 'en': 'Vaikuntha', 'telugu': 'వైకుణ్ఠ'}
guruvayupura = {'deva': 'गुरुवायुपुर', 'iast': 'Guruvāyupura', 'HK': 'guruvAyupura', 'en': 'Guruvayupura', 'telugu': 'గురువాయుపుర'}
koodaravalli = {'deva': 'कूडारवल्ली', 'iast': 'Kūḍāravallī', 'HK': 'kUDAravallI', 'en': 'Kudaravalli', 'telugu': 'కూడారవల్లీ'}
varahajayanti = {'deva': 'वराह~जयन्ती', 'iast': 'Varāha~Jayantī', 'HK': 'varAha~jayantI', 'en': 'Varaha Jayanti', 'telugu': 'వరాహ~జయన్తీ'}
vchaturthi = {'deva': 'श्रीविनायक-चतुर्थी', 'iast': 'Śrīvināyaka-chaturthī', 'HK': 'zrIvinAyaka-caturthI', 'en': 'Shrivinayaka-Chaturthi', 'telugu': 'శ్రీవినాయక-చతుర్థీ'}
ananta_chaturdashi = {'deva': 'अनन्त-चतुर्दशी', 'iast': 'Ananta-chaturdaśī', 'HK': 'ananta-caturdazI', 'en': 'Ananta-Chaturdashi', 'telugu': 'అనన్త-చతుర్దశీ'}
rishi_panchami = {'deva': 'ऋषि-पञ्चमी~व्रतम्', 'iast': 'Ṛṣi-pañchamī~Vratam', 'HK': 'RSi-paJcamI~vratam', 'en': 'á¹šshi-Panchami Vratam', 'telugu': 'ఋషి-పఞ్చమీ~వ్రతమ్'}
ramanavami = {'deva': 'श्रीरामनवमी', 'iast': 'Śrīrāmanavamī', 'HK': 'zrIrAmanavamI', 'en': 'Shriramanavami', 'telugu': 'శ్రీరామనవమీ'}
shivaratri = {'deva': 'महाशिवरात्रिः', 'iast': 'Mahāśivarātriḥ', 'HK': 'mahAzivarAtriH', 'en': 'Mahashivaratri', 'telugu': 'మహాశివరాత్రిః'}
janmashtami = {'deva': 'श्रीकृष्णजन्माष्टमी', 'iast': 'Śrīkṛṣṇajanmāṣṭamī', 'HK': 'zrIkRSNajanmASTamI', 'en': 'Shrikrishnajanmashtami', 'telugu': 'శ్రీకృష్ణజన్మాష్టమీ'}
chitra_purnima = {'deva': 'चित्रा~पूर्णिमा, ~गजेन्द्र-मोक्षः', 'iast': 'Chitrā~Pūrṇimā, Gajendra-mokṣaḥ', 'HK': 'citrA~pUrNimA, ~gajendra-mokSaH', 'en': 'Chitra Purnima, Gajendra-Moksha', 'telugu': 'చిత్రా~పూర్ణిమా, ~గజేన్ద్ర-మోక్షః'}
varalakshmi_vratam = {'deva': 'वरलक्ष्मी-व्रतम्', 'iast': 'Varalakṣmī-vratam', 'HK': 'varalakSmI-vratam', 'en': 'Varalakshmi-Vratam', 'telugu': 'వరలక్ష్మీ-వ్రతమ్'}
yajur_upakarma = {'deva': 'यजुर्वेद-उपाकर्म', 'iast': 'Yajurveda-upākarma', 'HK': 'yajurveda-upAkarma', 'en': 'Yajurveda-Upakarma', 'telugu': 'యజుర్వేద-ఉపాకర్మ'}
rg_upakarma = {'deva': 'ऋग्वेद-उपाकर्म', 'iast': 'Ṛgveda-upākarma', 'HK': 'Rgveda-upAkarma', 'en': 'á¹šgveda-Upakarma', 'telugu': 'ఋగ్వేద-ఉపాకర్మ'}
sama_upakarma = {'deva': 'सामवेद-उपाकर्म', 'iast': 'Sāmaveda-upākarma', 'HK': 'sAmaveda-upAkarma', 'en': 'Samaveda-Upakarma', 'telugu': 'సామవేద-ఉపాకర్మ'}
gayatri_japam = {'deva': 'गायत्री~जपम्', 'iast': 'Gāyatrī~Japam', 'HK': 'gAyatrI~japam', 'en': 'Gayatri Japam', 'telugu': 'గాయత్రీ~జపమ్'}
uttarayanam = {'deva': 'मकर~सङ्क्रान्ति/उत्तरायण-पुण्यकालम्', 'iast': 'Makara~Saṅkrānti/Uttarāyaṇa-puṇyakālam', 'HK': 'makara~saGkrAnti/uttarAyaNa-puNyakAlam', 'en': 'Makara Sankranti/Uttarayana-Punyakalam', 'telugu': 'మకర~సఙ్క్రాన్తి/ఉత్తరాయణ-పుణ్యకాలమ్'}
dakshinayanam = {'deva': 'दक्षिणायन-पुण्यकालम्', 'iast': 'Dakṣiṇāyana-puṇyakālam', 'HK': 'dakSiNAyana-puNyakAlam', 'en': 'Dakshinayana-Punyakalam', 'telugu': 'దక్షిణాయన-పుణ్యకాలమ్'}
mesha_sankranti = {'deva': 'मेष~सङ्क्रान्ति', 'iast': 'Meṣa~Saṅkrānti', 'HK': 'meSa~saGkrAnti', 'en': 'Mesha Sankranti', 'telugu': 'మేష~సఙ్క్రాన్తి'}
karadayan_nombu = {'deva': 'कारडयान्-नोम्बु', 'iast': 'Kāraḍayān-nombu', 'HK': 'kAraDayAn-nombu', 'en': 'Karadayan-Nombu', 'telugu': 'కారడయాన్-నోమ్బు'}
akshaya_tritiya = {'deva': 'अक्षय~तृतीया', 'iast': 'Akṣaya~Tṛtīyā', 'HK': 'akSaya~tRtIyA', 'en': 'Akshaya Tritiya', 'telugu': 'అక్షయ~తృతీయా'}
shankara_jayanti = {'deva': 'शङ्कर-जयन्ती', 'iast': 'Śaṅkara-jayantī', 'HK': 'zaGkara-jayantI', 'en': 'Shankara-Jayanti', 'telugu': 'శఙ్కర-జయన్తీ'}
mahalaya_paksham = {'deva': 'महालय-पक्ष~आरम्भः', 'iast': 'Mahālaya-pakṣa~Ārambhaḥ', 'HK': 'mahAlaya-pakSa~ArambhaH', 'en': 'Mahalaya-Paksha Arambha', 'telugu': 'మహాలయ-పక్ష~ఆరమ్భః'}
hanumat_jayanti = {'deva': 'श्री~हनूमत्~जयन्ती', 'iast': 'Śrī~Hanūmat~Jayantī', 'HK': 'zrI~hanUmat~jayantI', 'en': 'Shri Hanumat Jayanti', 'telugu': 'శ్రీ~హనూమత్~జయన్తీ'}
ardra_darshanam = {'deva': 'आर्द्रा~दर्शनम्', 'iast': 'Ārdrā~Darśanam', 'HK': 'ArdrA~darzanam', 'en': 'Ardra Darshanam', 'telugu': 'ఆర్ద్రా~దర్శనమ్'}
ratha_saptami = {'deva': 'रथ-सप्तमी', 'iast': 'Ratha-saptamī', 'HK': 'ratha-saptamI', 'en': 'Ratha-Saptami', 'telugu': 'రథ-సప్తమీ'}
goda_jayanti = {'deva': 'श्री~गोदा~जयन्ती', 'iast': 'Śrī~Godā~Jayantī', 'HK': 'zrI~godA~jayantI', 'en': 'Shri Goda Jayanti', 'telugu': 'శ్రీ~గోదా~జయన్తీ'}
adi_krittika = {'deva': 'आषाढ~कृत्तिका', 'iast': 'Āṣāḍha~Kṛttikā', 'HK': 'ASADha~kRttikA', 'en': 'Ashadha Krittika', 'telugu': 'ఆషాఢ~కృత్తికా'}
phalguni_uttaram = {'deva': 'फल्गुनी~उत्तरम्', 'iast': 'Phalgunī~Uttaram', 'HK': 'phalgunI~uttaram', 'en': 'Phalguni Uttaram', 'telugu': 'ఫల్గునీ~ఉత్తరమ్'}
mahalaya_amavasya = {'deva': 'महालय-अमावस्या', 'iast': 'Mahālaya-amāvasyā', 'HK': 'mahAlaya-amAvasyA', 'en': 'Mahalaya-Amavasya', 'telugu': 'మహాలయ-అమావస్యా'}
uma_maheshvara_vratam = {'deva': 'उमा-महेश्वर~व्रतम्', 'iast': 'Umā-maheśvara~Vratam', 'HK': 'umA-mahezvara~vratam', 'en': 'Uma-Maheshvara Vratam', 'telugu': 'ఉమా-మహేశ్వర~వ్రతమ్'}
yugadi = {'deva': 'युगादि', 'iast': 'Yugādi', 'HK': 'yugAdi', 'en': 'Yugadi', 'telugu': 'యుగాది'}
gauri_tritiya = {'deva': 'गौरी~तृतीया', 'iast': 'Gaurī~Tṛtīyā', 'HK': 'gaurI~tRtIyA', 'en': 'Gauri Tritiya', 'telugu': 'గౌరీ~తృతీయా'}
matsya_jayanti = {'deva': 'मत्स्य~जयन्ती', 'iast': 'Matsya~Jayantī', 'HK': 'matsya~jayantI', 'en': 'Matsya Jayanti', 'telugu': 'మత్స్య~జయన్తీ'}
parashurama_jayanti = {'deva': 'परशुराम~जयन्ती', 'iast': 'Paraśurāma~Jayantī', 'HK': 'parazurAma~jayantI', 'en': 'Parashurama Jayanti', 'telugu': 'పరశురామ~జయన్తీ'}
ganga_saptami = {'deva': 'गङ्गा~सप्तमी', 'iast': 'Gaṅgā~Saptamī', 'HK': 'gaGgA~saptamI', 'en': 'Ganga Saptami', 'telugu': 'గఙ్గా~సప్తమీ'}
nrisimha_jayanti = {'deva': 'नृसिंह~जयन्ती', 'iast': 'Nṛsiṃha~Jayantī', 'HK': 'nRsiMha~jayantI', 'en': 'Nrisimha Jayanti', 'telugu': 'నృసింహ~జయన్తీ'}
kurma_jayanti = {'deva': 'कूर्म~जयन्ती', 'iast': 'Kūrma~Jayantī', 'HK': 'kUrma~jayantI', 'en': 'Kurma Jayanti', 'telugu': 'కూర్మ~జయన్తీ'}
hayagriva_jayanti = {'deva': 'हयग्रीव~जयन्ती', 'iast': 'Hayagrīva~Jayantī', 'HK': 'hayagrIva~jayantI', 'en': 'Hayagriva Jayanti', 'telugu': 'హయగ్రీవ~జయన్తీ'}
bahula_chaturthi = {'deva': 'बहुला~चतुर्थी', 'iast': 'Bahulā~Chaturthī', 'HK': 'bahulA~caturthI', 'en': 'Bahula Chaturthi', 'telugu': 'బహులా~చతుర్థీ'}
radhashtami = {'deva': 'राधाष्टमी', 'iast': 'Rādhāṣṭamī', 'HK': 'rAdhASTamI', 'en': 'Radhashtami', 'telugu': 'రాధాష్టమీ'}
vamana_jayanti = {'deva': 'वामन~जयन्ती', 'iast': 'Vāmana~Jayantī', 'HK': 'vAmana~jayantI', 'en': 'Vamana Jayanti', 'telugu': 'వామన~జయన్తీ'}
buddha_jayanti = {'deva': 'बुद्ध~जयन्ती', 'iast': 'Buddha~Jayantī', 'HK': 'buddha~jayantI', 'en': 'Buddha Jayanti', 'telugu': 'బుద్ధ~జయన్తీ'}
govatsa_dvadashi = {'deva': 'गोवत्स~द्वादशी', 'iast': 'Govatsa~Dvādaśī', 'HK': 'govatsa~dvAdazI', 'en': 'Govatsa Dvadashi', 'telugu': 'గోవత్స~ద్వాదశీ'}
gopashtami = {'deva': 'गोपाष्टमी', 'iast': 'Gopāṣṭamī', 'HK': 'gopASTamI', 'en': 'Gopashtami', 'telugu': 'గోపాష్టమీ'}
tulasi_vivaha = {'deva': 'प्रबोधोत्सवः/तुलसी-विवाहः', 'iast': 'Prabodhotsavaḥ/tulasī-vivāhaḥ', 'HK': 'prabodhotsavaH/tulasI-vivAhaH', 'en': 'Prabodhotsava/Tulasi-Vivaha', 'telugu': 'ప్రబోధోత్సవః/తులసీ-వివాహః'}
tripurotsava = {'deva': 'त्रिपुरोत्सवः', 'iast': 'Tripurotsavaḥ', 'HK': 'tripurotsavaH', 'en': 'Tripurotsava', 'telugu': 'త్రిపురోత్సవః'}
maha_kartiki = {'deva': 'महा-कार्तिकी', 'iast': 'Mahā-kārtikī', 'HK': 'mahA-kArtikI', 'en': 'Maha-Kartiki', 'telugu': 'మహా-కార్తికీ'}
dattatreya_jayanti = {'deva': 'दत्तात्रेय~जयन्ती', 'iast': 'Dattātreya~Jayantī', 'HK': 'dattAtreya~jayantI', 'en': 'Dattatreya Jayanti', 'telugu': 'దత్తాత్రేయ~జయన్తీ'}
bhishmashtami = {'deva': 'भीष्माष्टमी', 'iast': 'Bhīṣmāṣṭamī', 'HK': 'bhISmASTamI', 'en': 'Bhishmashtami', 'telugu': 'భీష్మాష్టమీ'}
bahula_panchami = {'deva': 'बहुल~पञ्चमी/त्यागराज आराधना', 'iast': 'Bahula~Pañchamī/Tyāgarāja ārādhanā', 'HK': 'bahula~paJcamI/tyAgarAja ArAdhanA', 'en': 'Bahula Panchami/Tyagaraja Aradhana', 'telugu': 'బహుల~పఞ్చమీ/త్యాగరాజ ఆరాధనా'}
bhishma_dvadashi = {'deva': 'भीष्म-द्वादशी', 'iast': 'Bhīṣma-dvādaśī', 'HK': 'bhISma-dvAdazI', 'en': 'Bhishma-Dvadashi', 'telugu': 'భీష్మ-ద్వాదశీ'}
holika_purnima = {'deva': 'होलिका~पूर्णिमा', 'iast': 'Holikā~Pūrṇimā', 'HK': 'holikA~pUrNimA', 'en': 'Holika Purnima', 'telugu': 'హోలికా~పూర్ణిమా'}
chandra_grahanam = {'deva': 'चन्द्र-ग्रहणम्', 'iast': 'Chandra-grahaṇam', 'HK': 'candra-grahaNam', 'en': 'Chandra-Grahanam', 'telugu': 'చన్ద్ర-గ్రహణమ్'}
surya_grahanam = {'deva': 'सूर्य-ग्रहणम्', 'iast': 'Sūrya-grahaṇam', 'HK': 'sUrya-grahaNam', 'en': 'Surya-Grahanam', 'telugu': 'సూర్య-గ్రహణమ్'}
list_of_festivals = {'deva': 'मासान्तर-विशेषाः', 'iast': 'Māsāntara-viśeṣāḥ', 'HK': 'mAsAntara-vizeSAH', 'en': 'Masantara-Vishesha', 'telugu': 'మాసాన్తర-విశేషాః'}
chaturmasya_start = {'deva': 'चातुर्मासस्य~आरम्भः', 'iast': 'Chāturmāsasya~Ārambhaḥ', 'HK': 'cAturmAsasya~ArambhaH', 'en': 'Chaturmasasya Arambha', 'telugu': 'చాతుర్మాసస్య~ఆరమ్భః'}
chaturmasya_end = {'deva': 'चातुर्मासस्य~समापनम्', 'iast': 'Chāturmāsasya~Samāpanam', 'HK': 'cAturmAsasya~samApanam', 'en': 'Chaturmasasya Samapanam', 'telugu': 'చాతుర్మాసస్య~సమాపనమ్'}
nakshatra_names = {'deva': {1:'अश्विनी', 2:'अपभरणी', 3:'कृत्तिका', 4:'रोहिणी', 5:'मृगशीर्ष', 6:'आर्द्रा', 7:'पुनर्वसू', 8:'पुष्य', 9:'आश्रेषा', 10:'मघा', 11:'पूर्वफल्गुनी', 12:'उत्तरफल्गुनी', 13:'हस्त', 14:'चित्रा', 15:'स्वाति', 16:'विशाखा', 17:'अनूराधा', 18:'ज्येष्ठा', 19:'मूला', 20:'पूर्वाषाढा', 21:'उत्तराषाढा', 22:'श्रवण', 23:'श्रविष्ठा', 24:'शतभिषक्', 25:'पूर्वप्रोष्ठपदा', 26:'उत्तरप्रोष्ठपदा', 27:'रेवती'},
'iast': {1:'Aśvinī', 2:'Apabharaṇī', 3:'Kṛttikā', 4:'Rohiṇī', 5:'Mṛgaśīrṣa', 6:'Ārdrā', 7:'Punarvasū', 8:'Puṣya', 9:'Āśreṣā', 10:'Maghā', 11:'Pūrvaphalgunī', 12:'Uttaraphalgunī', 13:'Hasta', 14:'Chitrā', 15:'Svāti', 16:'Viśākhā', 17:'Anūrādhā', 18:'Jyeṣṭhā', 19:'Mūlā', 20:'Pūrvāṣāḍhā', 21:'Uttarāṣāḍhā', 22:'Śravaṇa', 23:'Śraviṣṭhā', 24:'Śatabhiṣak', 25:'Pūrvaproṣṭhapadā', 26:'Uttaraproṣṭhapadā', 27:'Revatī'},
'HK': {1:'azvinI', 2:'apabharaNI', 3:'kRttikA', 4:'rohiNI', 5:'mRgazIrSa', 6:'ArdrA', 7:'punarvasU', 8:'puSya', 9:'AzreSA', 10:'maghA', 11:'pUrvaphalgunI', 12:'uttaraphalgunI', 13:'hasta', 14:'citrA', 15:'svAti', 16:'vizAkhA', 17:'anUrAdhA', 18:'jyeSThA', 19:'mUlA', 20:'pUrvASADhA', 21:'uttarASADhA', 22:'zravaNa', 23:'zraviSThA', 24:'zatabhiSak', 25:'pUrvaproSThapadA', 26:'uttaraproSThapadA', 27:'revatI'},
'en': {1:'Ashvini', 2:'Apabharani', 3:'Krittika', 4:'Rohini', 5:'Mrigashirsha', 6:'Ardra', 7:'Punarvasu', 8:'Pushya', 9:'Ashresha', 10:'Magha', 11:'Purvaphalguni', 12:'Uttaraphalguni', 13:'Hasta', 14:'Chitra', 15:'Svati', 16:'Vishakha', 17:'Anuradha', 18:'Jyeshtha', 19:'Mula', 20:'Purvashadha', 21:'Uttarashadha', 22:'Shravana', 23:'Shravishtha', 24:'Shatabhishak', 25:'Purvaproshthapada', 26:'Uttaraproshthapada', 27:'Revati'},
'telugu': {1:'అశ్వినీ', 2:'అపభరణీ', 3:'కృత్తికా', 4:'రోహిణీ', 5:'మృగశీర్ష', 6:'ఆర్ద్రా', 7:'పునర్వసూ', 8:'పుష్య', 9:'ఆశ్రేషా', 10:'మఘా', 11:'పూర్వఫల్గునీ', 12:'ఉత్తరఫల్గునీ', 13:'హస్త', 14:'చిత్రా', 15:'స్వాతి', 16:'విశాఖా', 17:'అనూరాధా', 18:'జ్యేష్ఠా', 19:'మూలా', 20:'పూర్వాషాఢా', 21:'ఉత్తరాషాఢా', 22:'శ్రవణ', 23:'శ్రవిష్ఠా', 24:'శతభిషక్', 25:'పూర్వప్రోష్ఠపదా', 26:'ఉత్తరప్రోష్ఠపదా', 27:'రేవతీ'}}
masa_names = {'deva': {1:'मेष', 2:'वृषभ', 3:'मिथुन', 4:'कर्कटक', 5:'सिंह', 6:'कन्या', 7:'तुला', 8:'वृश्चिक', 9:'धनुः', 10:'मकर', 11:'कुम्भ', 12:'मीन'},
'iast': {1:'Meṣa', 2:'Vṛṣabha', 3:'Mithuna', 4:'Karkaṭaka', 5:'Siṃha', 6:'Kanyā', 7:'Tulā', 8:'Vṛśchika', 9:'Dhanuḥ', 10:'Makara', 11:'Kumbha', 12:'Mīna'},
'HK': {1:'meSa', 2:'vRSabha', 3:'mithuna', 4:'karkaTaka', 5:'siMha', 6:'kanyA', 7:'tulA', 8:'vRzcika', 9:'dhanuH', 10:'makara', 11:'kumbha', 12:'mIna'},
'en': {1:'Mesha', 2:'Vrishabha', 3:'Mithuna', 4:'Karkataka', 5:'Simha', 6:'Kanya', 7:'Tula', 8:'Vrishchika', 9:'Dhanu', 10:'Makara', 11:'Kumbha', 12:'Mina'},
'telugu': {1:'మేష', 2:'వృషభ', 3:'మిథున', 4:'కర్కటక', 5:'సింహ', 6:'కన్యా', 7:'తులా', 8:'వృశ్చిక', 9:'ధనుః', 10:'మకర', 11:'కుమ్భ', 12:'మీన'}}
chandra_masa_names = {'deva': {1:'चैत्र', 2:'वैशाख', 3:'ज्यैष्ठ', 4:'आषाढ', 5:'श्रवण', 6:'भाद्रपद', 7:'आश्विन', 8:'कार्तिक', 9:'मार्गशीर्ष', 10:'पौष', 11:'माघ', 12:'फाल्गुन'},
'iast': {1:'Chaitra', 2:'Vaiśākha', 3:'Jyaiṣṭha', 4:'Āṣāḍha', 5:'Śravaṇa', 6:'Bhādrapada', 7:'Āśvina', 8:'Kārtika', 9:'Mārgaśīrṣa', 10:'Pauṣa', 11:'Māgha', 12:'Phālguna'},
'HK': {1:'caitra', 2:'vaizAkha', 3:'jyaiSTha', 4:'ASADha', 5:'zravaNa', 6:'bhAdrapada', 7:'Azvina', 8:'kArtika', 9:'mArgazIrSa', 10:'pauSa', 11:'mAgha', 12:'phAlguna'},
'en': {1:'Chaitra', 2:'Vaishakha', 3:'Jyaishtha', 4:'Ashadha', 5:'Shravana', 6:'Bhadrapada', 7:'Ashvina', 8:'Kartika', 9:'Margashirsha', 10:'Pausha', 11:'Magha', 12:'Phalguna'},
'telugu': {1:'చైత్ర', 2:'వైశాఖ', 3:'జ్యైష్ఠ', 4:'ఆషాఢ', 5:'శ్రవణ', 6:'భాద్రపద', 7:'ఆశ్విన', 8:'కార్తిక', 9:'మార్గశీర్ష', 10:'పౌష', 11:'మాఘ', 12:'ఫాల్గున'}}
tithi_names = {'deva': {1:'शुक्ल~प्रथमा', 2:'शुक्ल~द्वितीया', 3:'शुक्ल~तृतीया', 4:'शुक्ल~चतुर्थी', 5:'शुक्ल~पञ्चमी', 6:'शुक्ल~षष्ठी', 7:'शुक्ल~सप्तमी', 8:'शुक्ल~अष्टमी', 9:'शुक्ल~नवमी', 10:'शुक्ल~दशमी', 11:'शुक्ल~एकादशी', 12:'शुक्ल~द्वादशी', 13:'शुक्ल~त्रयोदशी', 14:'शुक्ल~चतुर्दशी', 15:'पौर्णमासी', 16:'कृष्ण~प्रथमा', 17:'कृष्ण~द्वितीया', 18:'कृष्ण~तृतीया', 19:'कृष्ण~चतुर्थी', 20:'कृष्ण~पञ्चमी', 21:'कृष्ण~षष्ठी', 22:'कृष्ण~सप्तमी', 23:'कृष्ण~अष्टमी', 24:'कृष्ण~नवमी', 25:'कृष्ण~दशमी', 26:'कृष्ण~एकादशी', 27:'कृष्ण~द्वादशी', 28:'कृष्ण~त्रयोदशी', 29:'कृष्ण~चतुर्दशी', 30:'अमावास्या'},
'iast': {1:'Śukla~Prathamā', 2:'Śukla~Dvitīyā', 3:'Śukla~Tṛtīyā', 4:'Śukla~Chaturthī', 5:'Śukla~Pañchamī', 6:'Śukla~Ṣaṣṭhī', 7:'Śukla~Saptamī', 8:'Śukla~Aṣṭamī', 9:'Śukla~Navamī', 10:'Śukla~Daśamī', 11:'Śukla~Ekādaśī', 12:'Śukla~Dvādaśī', 13:'Śukla~Trayodaśī', 14:'Śukla~Chaturdaśī', 15:'Paurṇamāsī', 16:'Kṛṣṇa~Prathamā', 17:'Kṛṣṇa~Dvitīyā', 18:'Kṛṣṇa~Tṛtīyā', 19:'Kṛṣṇa~Chaturthī', 20:'Kṛṣṇa~Pañchamī', 21:'Kṛṣṇa~Ṣaṣṭhī', 22:'Kṛṣṇa~Saptamī', 23:'Kṛṣṇa~Aṣṭamī', 24:'Kṛṣṇa~Navamī', 25:'Kṛṣṇa~Daśamī', 26:'Kṛṣṇa~Ekādaśī', 27:'Kṛṣṇa~Dvādaśī', 28:'Kṛṣṇa~Trayodaśī', 29:'Kṛṣṇa~Chaturdaśī', 30:'Amāvāsyā'},
'HK': {1:'zukla~prathamA', 2:'zukla~dvitIyA', 3:'zukla~tRtIyA', 4:'zukla~caturthI', 5:'zukla~paJcamI', 6:'zukla~SaSThI', 7:'zukla~saptamI', 8:'zukla~aSTamI', 9:'zukla~navamI', 10:'zukla~dazamI', 11:'zukla~ekAdazI', 12:'zukla~dvAdazI', 13:'zukla~trayodazI', 14:'zukla~caturdazI', 15:'paurNamAsI', 16:'kRSNa~prathamA', 17:'kRSNa~dvitIyA', 18:'kRSNa~tRtIyA', 19:'kRSNa~caturthI', 20:'kRSNa~paJcamI', 21:'kRSNa~SaSThI', 22:'kRSNa~saptamI', 23:'kRSNa~aSTamI', 24:'kRSNa~navamI', 25:'kRSNa~dazamI', 26:'kRSNa~ekAdazI', 27:'kRSNa~dvAdazI', 28:'kRSNa~trayodazI', 29:'kRSNa~caturdazI', 30:'amAvAsyA'},
'en': {1:'Shukla Prathama', 2:'Shukla Dvitiya', 3:'Shukla Tritiya', 4:'Shukla Chaturthi', 5:'Shukla Panchami', 6:'Shukla Shashthi', 7:'Shukla Saptami', 8:'Shukla Ashtami', 9:'Shukla Navami', 10:'Shukla Dashami', 11:'Shukla Ekadashi', 12:'Shukla Dvadashi', 13:'Shukla Trayodashi', 14:'Shukla Chaturdashi', 15:'Paurnamasi', 16:'Krishna Prathama', 17:'Krishna Dvitiya', 18:'Krishna Tritiya', 19:'Krishna Chaturthi', 20:'Krishna Panchami', 21:'Krishna Shashthi', 22:'Krishna Saptami', 23:'Krishna Ashtami', 24:'Krishna Navami', 25:'Krishna Dashami', 26:'Krishna Ekadashi', 27:'Krishna Dvadashi', 28:'Krishna Trayodashi', 29:'Krishna Chaturdashi', 30:'Amavasya'},
'telugu': {1:'శుక్ల~ప్రథమా', 2:'శుక్ల~ద్వితీయా', 3:'శుక్ల~తృతీయా', 4:'శుక్ల~చతుర్థీ', 5:'శుక్ల~పఞ్చమీ', 6:'శుక్ల~షష్ఠీ', 7:'శుక్ల~సప్తమీ', 8:'శుక్ల~అష్టమీ', 9:'శుక్ల~నవమీ', 10:'శుక్ల~దశమీ', 11:'శుక్ల~ఏకాదశీ', 12:'శుక్ల~ద్వాదశీ', 13:'శుక్ల~త్రయోదశీ', 14:'శుక్ల~చతుర్దశీ', 15:'పౌర్ణమాసీ', 16:'కృష్ణ~ప్రథమా', 17:'కృష్ణ~ద్వితీయా', 18:'కృష్ణ~తృతీయా', 19:'కృష్ణ~చతుర్థీ', 20:'కృష్ణ~పఞ్చమీ', 21:'కృష్ణ~షష్ఠీ', 22:'కృష్ణ~సప్తమీ', 23:'కృష్ణ~అష్టమీ', 24:'కృష్ణ~నవమీ', 25:'కృష్ణ~దశమీ', 26:'కృష్ణ~ఏకాదశీ', 27:'కృష్ణ~ద్వాదశీ', 28:'కృష్ణ~త్రయోదశీ', 29:'కృష్ణ~చతుర్దశీ', 30:'అమావాస్యా'}}
year_names = {'deva': {1:'प्रभव', 2:'विभव', 3:'शुक्ल', 4:'प्रमोद', 5:'प्रजापति', 6:'आङ्गिरस', 7:'श्रीमुख', 8:'भाव', 9:'युव', 10:'धात्री', 11:'ईश्वर', 12:'बहुधान्य', 13:'प्रमाधि', 14:'विक्रम', 15:'वृष', 16:'चित्रभानु', 17:'स्वभानु', 18:'तारण', 19:'पार्थिव', 20:'व्यय', 21:'सर्वजित्', 22:'सर्वधारी', 23:'विरोधी', 24:'विकृति', 25:'खर', 26:'नन्दन', 27:'विजय', 28:'जय', 29:'मन्मथ', 30:'दुर्मुखी', 31:'हेविलम्बी', 32:'विलम्बी', 33:'विकारी', 34:'शार्वरी', 35:'प्लव', 36:'शुभकृत्', 37:'शोभकृत्', 38:'क्रोधी', 39:'विश्वावसु', 40:'पराभव', 41:'प्लवङ्ग', 42:'कीलक', 43:'सौम्य', 44:'साधारण', 45:'विरोधिकृति', 46:'परिधावी', 47:'प्रमादीच', 48:'आनन्द', 49:'राक्षस', 50:'नल', 51:'पिङ्गल', 52:'कलायुक्ति', 53:'सिद्धार्थी', 54:'रौद्र', 55:'दुर्मति', 56:'दुन्दुभि', 57:'रुधिरोद्गारी', 58:'रक्ताक्षी', 59:'क्रोधन', 60:'अक्षय'},
'iast': {1:'Prabhava', 2:'Vibhava', 3:'Śukla', 4:'Pramoda', 5:'Prajāpati', 6:'Āṅgirasa', 7:'Śrīmukha', 8:'Bhāva', 9:'Yuva', 10:'Dhātrī', 11:'Īśvara', 12:'Bahudhānya', 13:'Pramādhi', 14:'Vikrama', 15:'Vṛṣa', 16:'Chitrabhānu', 17:'Svabhānu', 18:'Tāraṇa', 19:'Pārthiva', 20:'Vyaya', 21:'Sarvajit', 22:'Sarvadhārī', 23:'Virodhī', 24:'Vikṛti', 25:'Khara', 26:'Nandana', 27:'Vijaya', 28:'Jaya', 29:'Manmatha', 30:'Durmukhī', 31:'Hevilambī', 32:'Vilambī', 33:'Vikārī', 34:'Śārvarī', 35:'Plava', 36:'Śubhakṛt', 37:'Śobhakṛt', 38:'Krodhī', 39:'Viśvāvasu', 40:'Parābhava', 41:'Plavaṅga', 42:'Kīlaka', 43:'Saumya', 44:'Sādhāraṇa', 45:'Virodhikṛti', 46:'Paridhāvī', 47:'Pramādīcha', 48:'Ānanda', 49:'Rākṣasa', 50:'Nala', 51:'Piṅgala', 52:'Kalāyukti', 53:'Siddhārthī', 54:'Raudra', 55:'Durmati', 56:'Dundubhi', 57:'Rudhirodgārī', 58:'Raktākṣī', 59:'Krodhana', 60:'Akṣaya'},
'HK': {1:'prabhava', 2:'vibhava', 3:'zukla', 4:'pramoda', 5:'prajApati', 6:'AGgirasa', 7:'zrImukha', 8:'bhAva', 9:'yuva', 10:'dhAtrI', 11:'Izvara', 12:'bahudhAnya', 13:'pramAdhi', 14:'vikrama', 15:'vRSa', 16:'citrabhAnu', 17:'svabhAnu', 18:'tAraNa', 19:'pArthiva', 20:'vyaya', 21:'sarvajit', 22:'sarvadhArI', 23:'virodhI', 24:'vikRti', 25:'khara', 26:'nandana', 27:'vijaya', 28:'jaya', 29:'manmatha', 30:'durmukhI', 31:'hevilambI', 32:'vilambI', 33:'vikArI', 34:'zArvarI', 35:'plava', 36:'zubhakRt', 37:'zobhakRt', 38:'krodhI', 39:'vizvAvasu', 40:'parAbhava', 41:'plavaGga', 42:'kIlaka', 43:'saumya', 44:'sAdhAraNa', 45:'virodhikRti', 46:'paridhAvI', 47:'pramAdIca', 48:'Ananda', 49:'rAkSasa', 50:'nala', 51:'piGgala', 52:'kalAyukti', 53:'siddhArthI', 54:'raudra', 55:'durmati', 56:'dundubhi', 57:'rudhirodgArI', 58:'raktAkSI', 59:'krodhana', 60:'akSaya'},
'en': {1:'Prabhava', 2:'Vibhava', 3:'Shukla', 4:'Pramoda', 5:'Prajapati', 6:'Angirasa', 7:'Shrimukha', 8:'Bhava', 9:'Yuva', 10:'Dhatri', 11:'Äªshvara', 12:'Bahudhanya', 13:'Pramadhi', 14:'Vikrama', 15:'Vrisha', 16:'Chitrabhanu', 17:'Svabhanu', 18:'Tarana', 19:'Parthiva', 20:'Vyaya', 21:'Sarvajit', 22:'Sarvadhari', 23:'Virodhi', 24:'Vikriti', 25:'Khara', 26:'Nandana', 27:'Vijaya', 28:'Jaya', 29:'Manmatha', 30:'Durmukhi', 31:'Hevilambi', 32:'Vilambi', 33:'Vikari', 34:'Sharvari', 35:'Plava', 36:'Shubhakrit', 37:'Shobhakrit', 38:'Krodhi', 39:'Vishvavasu', 40:'Parabhava', 41:'Plavanga', 42:'Kilaka', 43:'Saumya', 44:'Sadharana', 45:'Virodhikriti', 46:'Paridhavi', 47:'Pramadicha', 48:'Ananda', 49:'Rakshasa', 50:'Nala', 51:'Pingala', 52:'Kalayukti', 53:'Siddharthi', 54:'Raudra', 55:'Durmati', 56:'Dundubhi', 57:'Rudhirodgari', 58:'Raktakshi', 59:'Krodhana', 60:'Akshaya'},
'telugu': {1:'ప్రభవ', 2:'విభవ', 3:'శుక్ల', 4:'ప్రమోద', 5:'ప్రజాపతి', 6:'ఆఙ్గిరస', 7:'శ్రీముఖ', 8:'భావ', 9:'యువ', 10:'ధాత్రీ', 11:'ఈశ్వర', 12:'బహుధాన్య', 13:'ప్రమాధి', 14:'విక్రమ', 15:'వృష', 16:'చిత్రభాను', 17:'స్వభాను', 18:'తారణ', 19:'పార్థివ', 20:'వ్యయ', 21:'సర్వజిత్', 22:'సర్వధారీ', 23:'విరోధీ', 24:'వికృతి', 25:'ఖర', 26:'నన్దన', 27:'విజయ', 28:'జయ', 29:'మన్మథ', 30:'దుర్ముఖీ', 31:'హేవిలమ్బీ', 32:'విలమ్బీ', 33:'వికారీ', 34:'శార్వరీ', 35:'ప్లవ', 36:'శుభకృత్', 37:'శోభకృత్', 38:'క్రోధీ', 39:'విశ్వావసు', 40:'పరాభవ', 41:'ప్లవఙ్గ', 42:'కీలక', 43:'సౌమ్య', 44:'సాధారణ', 45:'విరోధికృతి', 46:'పరిధావీ', 47:'ప్రమాదీచ', 48:'ఆనన్ద', 49:'రాక్షస', 50:'నల', 51:'పిఙ్గల', 52:'కలాయుక్తి', 53:'సిద్ధార్థీ', 54:'రౌద్ర', 55:'దుర్మతి', 56:'దున్దుభి', 57:'రుధిరోద్గారీ', 58:'రక్తాక్షీ', 59:'క్రోధన', 60:'అక్షయ'}}
karanam_names = {'deva': {1:'किंस्तुघ्न', 2:'बव', 3:'बालव', 4:'कौलव', 5:'तैतिल', 6:'गरज', 7:'वणिज', 8:'विष्टि (भद्र)', 9:'बव', 10:'बालव', 11:'कौलव', 12:'तैतिल', 13:'गरज', 14:'वणिज', 15:'विष्टि (भद्र)', 16:'बव', 17:'बालव', 18:'कौलव', 19:'तैतिल', 20:'गरज', 21:'वणिज', 22:'विष्टि (भद्र)', 23:'बव', 24:'बालव', 25:'कौलव', 26:'तैतिल', 27:'गरज', 28:'वणिज', 29:'विष्टि (भद्र)', 30:'बव', 31:'बालव', 32:'कौलव', 33:'तैतिल', 34:'गरज', 35:'वणिज', 36:'विष्टि (भद्र)', 37:'बव', 38:'बालव', 39:'कौलव', 40:'तैतिल', 41:'गरज', 42:'वणिज', 43:'विष्टि (भद्र)', 44:'बव', 45:'बालव', 46:'कौलव', 47:'तैतिल', 48:'गरज', 49:'वणिज', 50:'विष्टि (भद्र)', 51:'बव', 52:'बालव', 53:'कौलव', 54:'तैतिल', 55:'गरज', 56:'वणिज', 57:'विष्टि (भद्र)', 58:'शकुनि', 59:'चतुष्पात्', 60:'नागव'},
'iast': {1:'Kiṃstughna', 2:'Bava', 3:'Bālava', 4:'Kaulava', 5:'Taitila', 6:'Garaja', 7:'Vaṇija', 8:'Viṣṭi (Bhadra)', 9:'Bava', 10:'Bālava', 11:'Kaulava', 12:'Taitila', 13:'Garaja', 14:'Vaṇija', 15:'Viṣṭi (Bhadra)', 16:'Bava', 17:'Bālava', 18:'Kaulava', 19:'Taitila', 20:'Garaja', 21:'Vaṇija', 22:'Viṣṭi (Bhadra)', 23:'Bava', 24:'Bālava', 25:'Kaulava', 26:'Taitila', 27:'Garaja', 28:'Vaṇija', 29:'Viṣṭi (Bhadra)', 30:'Bava', 31:'Bālava', 32:'Kaulava', 33:'Taitila', 34:'Garaja', 35:'Vaṇija', 36:'Viṣṭi (Bhadra)', 37:'Bava', 38:'Bālava', 39:'Kaulava', 40:'Taitila', 41:'Garaja', 42:'Vaṇija', 43:'Viṣṭi (Bhadra)', 44:'Bava', 45:'Bālava', 46:'Kaulava', 47:'Taitila', 48:'Garaja', 49:'Vaṇija', 50:'Viṣṭi (Bhadra)', 51:'Bava', 52:'Bālava', 53:'Kaulava', 54:'Taitila', 55:'Garaja', 56:'Vaṇija', 57:'Viṣṭi (Bhadra)', 58:'Śakuni', 59:'Catuṣpāt', 60:'Nāgava'},
'HK': {1:'kiMstughna', 2:'bava', 3:'bAlava', 4:'kaulava', 5:'taitila', 6:'garaja', 7:'vaNija', 8:'viSTi (bhadra)', 9:'bava', 10:'bAlava', 11:'kaulava', 12:'taitila', 13:'garaja', 14:'vaNija', 15:'viSTi (bhadra)', 16:'bava', 17:'bAlava', 18:'kaulava', 19:'taitila', 20:'garaja', 21:'vaNija', 22:'viSTi (bhadra)', 23:'bava', 24:'bAlava', 25:'kaulava', 26:'taitila', 27:'garaja', 28:'vaNija', 29:'viSTi (bhadra)', 30:'bava', 31:'bAlava', 32:'kaulava', 33:'taitila', 34:'garaja', 35:'vaNija', 36:'viSTi (bhadra)', 37:'bava', 38:'bAlava', 39:'kaulava', 40:'taitila', 41:'garaja', 42:'vaNija', 43:'viSTi (bhadra)', 44:'bava', 45:'bAlava', 46:'kaulava', 47:'taitila', 48:'garaja', 49:'vaNija', 50:'viSTi (bhadra)', 51:'bava', 52:'bAlava', 53:'kaulava', 54:'taitila', 55:'garaja', 56:'vaNija', 57:'viSTi (bhadra)', 58:'zakuni', 59:'catuSpAt', 60:'nAgava'},
'en': {1:'Kimstughna', 2:'Bava', 3:'Balava', 4:'Kaulava', 5:'Taitila', 6:'Garaja', 7:'Vanija', 8:'Vishti (Bhadra)', 9:'Bava', 10:'Balava', 11:'Kaulava', 12:'Taitila', 13:'Garaja', 14:'Vanija', 15:'Vishti (Bhadra)', 16:'Bava', 17:'Balava', 18:'Kaulava', 19:'Taitila', 20:'Garaja', 21:'Vanija', 22:'Vishti (Bhadra)', 23:'Bava', 24:'Balava', 25:'Kaulava', 26:'Taitila', 27:'Garaja', 28:'Vanija', 29:'Vishti (Bhadra)', 30:'Bava', 31:'Balava', 32:'Kaulava', 33:'Taitila', 34:'Garaja', 35:'Vanija', 36:'Vishti (Bhadra)', 37:'Bava', 38:'Balava', 39:'Kaulava', 40:'Taitila', 41:'Garaja', 42:'Vanija', 43:'Vishti (Bhadra)', 44:'Bava', 45:'Balava', 46:'Kaulava', 47:'Taitila', 48:'Garaja', 49:'Vanija', 50:'Vishti (Bhadra)', 51:'Bava', 52:'Balava', 53:'Kaulava', 54:'Taitila', 55:'Garaja', 56:'Vanija', 57:'Vishti (Bhadra)', 58:'Shakuni', 59:'Chatushpat', 60:'Nagava'},
'telugu': {1:'కింస్తుఘ్న', 2:'బవ', 3:'బాలవ', 4:'కౌలవ', 5:'తైతిల', 6:'గరజ', 7:'వణిజ', 8:'విష్టి (భద్ర)', 9:'బవ', 10:'బాలవ', 11:'కౌలవ', 12:'తైతిల', 13:'గరజ', 14:'వణిజ', 15:'విష్టి (భద్ర)', 16:'బవ', 17:'బాలవ', 18:'కౌలవ', 19:'తైతిల', 20:'గరజ', 21:'వణిజ', 22:'విష్టి (భద్ర)', 23:'బవ', 24:'బాలవ', 25:'కౌలవ', 26:'తైతిల', 27:'గరజ', 28:'వణిజ', 29:'విష్టి (భద్ర)', 30:'బవ', 31:'బాలవ', 32:'కౌలవ', 33:'తైతిల', 34:'గరజ', 35:'వణిజ', 36:'విష్టి (భద్ర)', 37:'బవ', 38:'బాలవ', 39:'కౌలవ', 40:'తైతిల', 41:'గరజ', 42:'వణిజ', 43:'విష్టి (భద్ర)', 44:'బవ', 45:'బాలవ', 46:'కౌలవ', 47:'తైతిల', 48:'గరజ', 49:'వణిజ', 50:'విష్టి (భద్ర)', 51:'బవ', 52:'బాలవ', 53:'కౌలవ', 54:'తైతిల', 55:'గరజ', 56:'వణిజ', 57:'విష్టి (భద్ర)', 58:'శకుని', 59:'చతుష్పాత్', 60:'నాగవ'}}
yogam_names = {'deva': {1:'विष्कुम्भ', 2:'प्रीति', 3:'आयुष्मान्', 4:'सौभाग्य', 5:'शोभन', 6:'अतिगण्ड', 7:'सुकर्म', 8:'धृति', 9:'शूल', 10:'गण्ड', 11:'वृद्धि', 12:'ध्रुव', 13:'व्याघात', 14:'हर्षण', 15:'वज्र', 16:'सिद्धि', 17:'व्यतीपात', 18:'वरीयान्', 19:'परिघ', 20:'शिव', 21:'सिद्ध', 22:'साध्य', 23:'शुभ', 24:'शुक्ल', 25:'ब्रह्म', 26:'इन्द्र', 27:'वैधृति'},
'iast': {1:'Viṣkumbha', 2:'Prīti', 3:'Āyuṣmān', 4:'Saubhāgya', 5:'Śobhana', 6:'Atigaṇḍa', 7:'Sukarma', 8:'Dhṛti', 9:'Śūla', 10:'Gaṇḍa', 11:'Vṛddhi', 12:'Dhruva', 13:'Vyāghāta', 14:'Harṣaṇa', 15:'Vajra', 16:'Siddhi', 17:'Vyatīpāta', 18:'Varīyān', 19:'Parigha', 20:'Śiva', 21:'Siddha', 22:'Sādhya', 23:'Śubha', 24:'Śukla', 25:'Brahma', 26:'Indra', 27:'Vaidhṛti'},
'HK': {1:'viSkumbha', 2:'prIti', 3:'AyuSmAn', 4:'saubhAgya', 5:'zobhana', 6:'atigaNDa', 7:'sukarma', 8:'dhRti', 9:'zUla', 10:'gaNDa', 11:'vRddhi', 12:'dhruva', 13:'vyAghAta', 14:'harSaNa', 15:'vajra', 16:'siddhi', 17:'vyatIpAta', 18:'varIyAn', 19:'parigha', 20:'ziva', 21:'siddha', 22:'sAdhya', 23:'zubha', 24:'zukla', 25:'brahma', 26:'indra', 27:'vaidhRti'},
'en': {1:'Vishkumbha', 2:'Priti', 3:'Ayushman', 4:'Saubhagya', 5:'Shobhana', 6:'Atiganda', 7:'Sukarma', 8:'Dhriti', 9:'Shula', 10:'Ganda', 11:'Vriddhi', 12:'Dhruva', 13:'Vyaghata', 14:'Harshana', 15:'Vajra', 16:'Siddhi', 17:'Vyatipata', 18:'Variyan', 19:'Parigha', 20:'Shiva', 21:'Siddha', 22:'Sadhya', 23:'Shubha', 24:'Shukla', 25:'Brahma', 26:'Indra', 27:'Vaidhriti'},
'telugu': {1:'విష్కుమ్భ', 2:'ప్రీతి', 3:'ఆయుష్మాన్', 4:'సౌభాగ్య', 5:'శోభన', 6:'అతిగణ్డ', 7:'సుకర్మ', 8:'ధృతి', 9:'శూల', 10:'గణ్డ', 11:'వృద్ధి', 12:'ధ్రువ', 13:'వ్యాఘాత', 14:'హర్షణ', 15:'వజ్ర', 16:'సిద్ధి', 17:'వ్యతీపాత', 18:'వరీయాన్', 19:'పరిఘ', 20:'శివ', 21:'సిద్ధ', 22:'సాధ్య', 23:'శుభ', 24:'శుక్ల', 25:'బ్రహ్మ', 26:'ఇన్ద్ర', 27:'వైధృతి'}}
shukla_ekadashi_names = {'deva': {1:'कामदा', 2:'मोहिनी', 3:'पाण्डव~निर्जला', 4:'पद्मा/देवशयनी', 5:'पवित्रोपान', 6:'परिवर्तिनी', 7:'पापाङ्कुशा', 8:'उत्तान/देवप्रबोधिनी', 9:'मोक्षदा', 10:'पुत्रदा', 11:'जया', 12:'आमलकी', 13:'पद्मिनी'},
'iast': {1:'Kāmadā', 2:'Mohinī', 3:'Pāṇḍava~Nirjalā', 4:'Padmā/Devaśayanī', 5:'Pavitropāna', 6:'Parivartinī', 7:'Pāpāṅkuśā', 8:'Uttāna/Devaprabodhinī', 9:'Mokṣadā', 10:'Putradā', 11:'Jayā', 12:'Āmalakī', 13:'Padminī'},
'HK': {1:'kAmadA', 2:'mohinI', 3:'pANDava~nirjalA', 4:'padmA/devazayanI', 5:'pavitropAna', 6:'parivartinI', 7:'pApAGkuzA', 8:'uttAna/devaprabodhinI', 9:'mokSadA', 10:'putradA', 11:'jayA', 12:'AmalakI', 13:'padminI'},
'en': {1:'Kamada', 2:'Mohini', 3:'Pandava Nirjala', 4:'Padma/Devashayani', 5:'Pavitropana', 6:'Parivartini', 7:'Papankusha', 8:'Uttana/Devaprabodhini', 9:'Mokshada', 10:'Putrada', 11:'Jaya', 12:'Amalaki', 13:'Padmini'},
'telugu': {1:'కామదా', 2:'మోహినీ', 3:'పాణ్డవ~నిర్జలా', 4:'పద్మా/దేవశయనీ', 5:'పవిత్రోపాన', 6:'పరివర్తినీ', 7:'పాపాఙ్కుశా', 8:'ఉత్తాన/దేవప్రబోధినీ', 9:'మోక్షదా', 10:'పుత్రదా', 11:'జయా', 12:'ఆమలకీ', 13:'పద్మినీ'}}
krishna_ekadashi_names = {'deva': {1:'पापमोचनी', 2:'वरूथिनी', 3:'अपरा', 4:'योगिनी', 5:'कामिका', 6:'अजा', 7:'इन्दिरा', 8:'रमा', 9:'उत्पन्ना', 10:'सफला', 11:'षट्तिला', 12:'विजया', 13:'परमा'},
'iast': {1:'Pāpamochanī', 2:'Varūthinī', 3:'Aparā', 4:'Yoginī', 5:'Kāmikā', 6:'Ajā', 7:'Indirā', 8:'Ramā', 9:'Utpannā', 10:'Saphalā', 11:'Ṣaṭtilā', 12:'Vijayā', 13:'Paramā'},
'HK': {1:'pApamocanI', 2:'varUthinI', 3:'aparA', 4:'yoginI', 5:'kAmikA', 6:'ajA', 7:'indirA', 8:'ramA', 9:'utpannA', 10:'saphalA', 11:'SaTtilA', 12:'vijayA', 13:'paramA'},
'en': {1:'Papamochani', 2:'Varuthini', 3:'Apara', 4:'Yogini', 5:'Kamika', 6:'Aja', 7:'Indira', 8:'Rama', 9:'Utpanna', 10:'Saphala', 11:'Shattila', 12:'Vijaya', 13:'Parama'},
'telugu': {1:'పాపమోచనీ', 2:'వరూథినీ', 3:'అపరా', 4:'యోగినీ', 5:'కామికా', 6:'అజా', 7:'ఇన్దిరా', 8:'రమా', 9:'ఉత్పన్నా', 10:'సఫలా', 11:'షట్తిలా', 12:'విజయా', 13:'పరమా'}}
